name: Deploy to Render

on:
  push:
    branches: [ "main" ]

jobs:
  render_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Display SoftUni UserName
      run: echo "SoftUni UserName - daniel123123"

    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Deploy the App to Render
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_DEPLOY_HOOK }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
